package second;

public enum Type {
	GREEN_ALGAE, CHLOROPHYTA, CHAROPHYTA, LAND_PLANTS, NON_VASCULAR_PLANTS, LIVERWORTS, MOSSES, HORNWORTS,
	HORNEOPHYTOPSIDA, VASCULAR_PLANTS, LYCOPODIOPHYTA_CLUBMOSSES, PTERIDOPHYTA, PTERIDOPSIDA, SPHENOPSIDA,
	MARATTIOPSIDA, PSILOTOPSIDA, RHYNIOPHYTA, ZOSTEROPHYLLOPHYTA, TRIMEROPHYTOPHYTA, PROGYMNOSPERMOPHYTA, SEED_PLANTS,
	PTERIDOSPERMATOPHYTA, PINOPHYTA, CYCADOPHYTA, GINKGOPHYTA, GNETOPHYTA, MAGNOLIOPHYTA, DICOTYLEDONS, MONOCOTYLEDONS,
	NEMATOPHYTES
}
